# Generated by Django 4.2 on 2023-06-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageprice',
            options={'verbose_name': 'Пакет цен', 'verbose_name_plural': ' Пакеты цен'},
        ),
    ]
