# Generated by Django 4.2 on 2023-06-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('appearance', models.CharField(choices=[('Азиатская', 'aзиатская'), ('Европейская', 'европейская'), ('Экзотика', 'экзотика')], max_length=20)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('eyes', models.CharField(choices=[('Карие', 'карие'), ('Черные', 'черные'), ('Зеленые', 'зеленые'), ('Голубые', 'голубые'), ('Серые', 'серые')], max_length=20)),
                ('hairs', models.CharField(choices=[('Брюнетка', 'брюнетка'), ('Блондинка', 'блондинка'), ('Шатенка', 'шатенка'), ('Рыжие', 'рыжие'), ('Мелированные', 'мелированные')], max_length=20)),
                ('type', models.CharField(choices=[('Индивидуалка', 'индивидуалка'), ('Салон', 'салон')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('breast', models.CharField(choices=[('0-1', '0-1'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4+', '4+')], max_length=20)),
                ('phone_number', models.CharField(max_length=16)),
                ('schedule', models.CharField(max_length=19)),
                ('speak_english', models.BooleanField(default=False)),
                ('is_trans', models.BooleanField(default=False)),
                ('in_osh', models.BooleanField(default=False)),
                ('additional_service', models.ManyToManyField(blank=True, to='services.additionalservice')),
                ('basic_service', models.ManyToManyField(to='services.basicservice')),
                ('extreme', models.ManyToManyField(blank=True, to='services.extreme')),
                ('massage', models.ManyToManyField(blank=True, to='services.massage')),
                ('package_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='services.packageprice')),
                ('sadomazo', models.ManyToManyField(blank=True, to='services.sadomazo')),
                ('striptease', models.ManyToManyField(blank=True, to='services.striptease')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='ModelsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='model_photos')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='models.model')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
