# Generated by Django 4.2 on 2023-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_model_options_alter_modelsgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
