# Generated by Django 4.2.2 on 2023-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_confirmationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
